// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserMonthlyBonusLog = "user_monthly_bonus_log"

// UserMonthlyBonusLog mapped from table <user_monthly_bonus_log>
type UserMonthlyBonusLog struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`         // ID
	UserID      int64          `gorm:"column:user_id;not null;comment:ID" json:"user_id"`                    // ID
	YearMonth   string         `gorm:"column:year_month;not null;comment:YYYYMM" json:"year_month"`          // YYYYMM
	BonusType   int32          `gorm:"column:bonus_type;not null;comment:1:3 2:7 3:15 4:" json:"bonus_type"` // 1:3 2:7 3:15 4:
	Description string         `gorm:"column:description" json:"description"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserMonthlyBonusLog's table name
func (*UserMonthlyBonusLog) TableName() string {
	return TableNameUserMonthlyBonusLog
}
