// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserPointsTransaction = "user_points_transactions"

// UserPointsTransaction mapped from table <user_points_transactions>
type UserPointsTransaction struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`   // ID
	UserID          int64          `gorm:"column:user_id;not null;comment:ID" json:"user_id"`              // ID
	PointsChange    int64          `gorm:"column:points_change;not null;comment: ()" json:"points_change"` //  ()
	CurrentBalance  int64          `gorm:"column:current_balance;not null" json:"current_balance"`
	TransactionType int32          `gorm:"column:transaction_type;not null;comment:(1: 2: 3: 4: 5:)" json:"transaction_type"` // (1: 2: 3: 4: 5:)
	Description     string         `gorm:"column:description" json:"description"`
	ExtJSON         string         `gorm:"column:ext_json;not null" json:"ext_json"`
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserPointsTransaction's table name
func (*UserPointsTransaction) TableName() string {
	return TableNameUserPointsTransaction
}
