// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserCheckinRecord = "user_checkin_records"

// UserCheckinRecord mapped from table <user_checkin_records>
type UserCheckinRecord struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID            int64          `gorm:"column:user_id;not null;comment:ID" json:"user_id"`            // ID
	CheckinDate       time.Time      `gorm:"column:checkin_date;not null" json:"checkin_date"`
	CheckinType       int32          `gorm:"column:checkin_type;not null;default:1;comment:1=2=" json:"checkin_type"` // 1=2=
	PointsAwardedBase int32          `gorm:"column:points_awarded_base;not null;default:1" json:"points_awarded_base"`
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserCheckinRecord's table name
func (*UserCheckinRecord) TableName() string {
	return TableNameUserCheckinRecord
}
