// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserPoint = "user_points"

// UserPoint mapped from table <user_points>
type UserPoint struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID      int64          `gorm:"column:user_id;not null;comment:ID" json:"user_id"`            // ID
	Points      int64          `gorm:"column:points" json:"points"`
	PointsTotal int64          `gorm:"column:points_total" json:"points_total"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserPoint's table name
func (*UserPoint) TableName() string {
	return TableNameUserPoint
}
