// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserinfo = "userinfo"

// Userinfo mapped from table <userinfo>
type Userinfo struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID    int64          `gorm:"column:user_id;not null;comment:ID" json:"user_id"`            // ID
	Username  string         `gorm:"column:username;not null" json:"username"`
	Password  string         `gorm:"column:password;not null;comment:(MD5)" json:"password"` // (MD5)
	Email     string         `gorm:"column:email" json:"email"`
	Avatar    string         `gorm:"column:avatar" json:"avatar"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Userinfo's table name
func (*Userinfo) TableName() string {
	return TableNameUserinfo
}
